<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['web_access_control_add_time'] = 'Добавить Период времени';
$lang['web_access_control_app_description'] = 'Управление веб-доступом позволяет администратору соблюдать время, день веб-доступа группам или компьютерам по (IP или MAC-адресу), используя веб-прокси.';
$lang['web_access_control_app_name'] = 'Управление веб-доступом';
$lang['web_access_control_apply_group'] = 'Применить доступ к группе';
$lang['web_access_control_apply_ip'] = 'Применить контроль к IP-адрес';
$lang['web_access_control_apply_mac'] = 'Применить контроль к MAC-адресу';
$lang['web_access_control_ctrl_click'] = '(CTRL-щелкните для множественных выборов)';
$lang['web_access_control_day_of_week'] = 'День недели';
$lang['web_access_control_end_time'] = 'Время окончания';
$lang['web_access_control_id_method'] = 'Метод идентификации';
$lang['web_access_control_list'] = 'Список управления доступом';
$lang['web_access_control_name'] = 'Имя';
$lang['web_access_control_outside'] = 'Вне';
$lang['web_access_control_outside_range'] = 'Нет ограничений по времени';
$lang['web_access_control_priority'] = 'Приоритет';
$lang['web_access_control_start_time'] = 'Время начала';
$lang['web_access_control_time_definitions'] = 'Определения времени суток';
$lang['web_access_control_time_delete_warning'] = 'Внимание: все записи контроля доступа, использующие это определение времени будут удалены.';
$lang['web_access_control_time_of_day'] = 'Время суток';
$lang['web_access_control_time_restriction'] = 'Ограничение';
$lang['web_access_control_time_rule'] = 'Управление доступом по времени суток';
$lang['web_access_control_type'] = 'Тип';
$lang['web_access_control_web_access_control'] = 'Управление веб-доступом';
$lang['web_access_control_within'] = 'В пределах';
$lang['web_access_control_within_range'] = 'Ограничения по времени';
