<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['web_access_control_add_time'] = 'Lägg till tidsperiod';
$lang['web_access_control_app_description'] = 'Kontrollsystem för åtkomst till Internet gör att en administratör kan ställa in tidpunkter för åtkomst till Internet för en grupp eller datorer (IP eller MAC-adress) genom användandet av proxy.';
$lang['web_access_control_app_name'] = 'Åtkomstkontroll till Internet';
$lang['web_access_control_apply_group'] = 'Aktivera åtkomstkontroll för grupp';
$lang['web_access_control_apply_ip'] = 'Aktivera åtkomstkontroll för IP-adress';
$lang['web_access_control_apply_mac'] = 'Aktivera åtkomstkontroll för MAC-adress';
$lang['web_access_control_ctrl_click'] = '(CTRL-klicka för multipla val)';
$lang['web_access_control_day_of_week'] = 'Veckodag';
$lang['web_access_control_end_time'] = 'Sluttid';
$lang['web_access_control_id_method'] = 'Identifieringsmetod';
$lang['web_access_control_list'] = 'Lista över åtkomstkontrollen';
$lang['web_access_control_name'] = 'Namn';
$lang['web_access_control_outside'] = 'Utanför';
$lang['web_access_control_outside_range'] = 'Utanför tidsrestriktioner';
$lang['web_access_control_priority'] = 'Prioritet';
$lang['web_access_control_start_time'] = 'Starttid';
$lang['web_access_control_time_definitions'] = 'Defenitioner av veckodagar';
$lang['web_access_control_time_delete_warning'] = 'Varning: all data för åtkomstkontroll som använder denna tidsdefinition kommer att raderas.';
$lang['web_access_control_time_of_day'] = 'Tid på dagen';
$lang['web_access_control_time_restriction'] = 'Restriktion';
$lang['web_access_control_time_rule'] = 'Åtkomstkontroll för tid på dagen';
$lang['web_access_control_type'] = 'Typ';
$lang['web_access_control_web_access_control'] = 'Åtkomstkontroll för Internet';
$lang['web_access_control_within'] = 'Inom';
$lang['web_access_control_within_range'] = 'Inom tidsrestriktionerna';
