<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['web_access_control_add_time'] = 'Add Time Period';
$lang['web_access_control_app_description'] = 'Web Access Control allows an administrator to enforce time-of-day web access to groups or computers (IP or MAC address) using the web proxy.';
$lang['web_access_control_app_name'] = 'Web Access Control';
$lang['web_access_control_apply_group'] = 'Apply Access Control to Group';
$lang['web_access_control_apply_ip'] = 'Apply Access Control to IP Address';
$lang['web_access_control_apply_mac'] = 'Apply Access Control to MAC Address';
$lang['web_access_control_ctrl_click'] = '(CTRL-click for multiple selections)';
$lang['web_access_control_day_of_week'] = 'Day of Week';
$lang['web_access_control_end_time'] = 'End Time';
$lang['web_access_control_id_method'] = 'Method of Identification';
$lang['web_access_control_list'] = 'Access Control List';
$lang['web_access_control_name'] = 'Name';
$lang['web_access_control_outside'] = 'Outside';
$lang['web_access_control_outside_range'] = 'Outside time restrictions';
$lang['web_access_control_priority'] = 'Priority';
$lang['web_access_control_start_time'] = 'Start Time';
$lang['web_access_control_time_definitions'] = 'Time of Day Definitions';
$lang['web_access_control_time_delete_warning'] = 'Warning: any access control entries using this time definition will be deleted.';
$lang['web_access_control_time_of_day'] = 'Time of Day';
$lang['web_access_control_time_restriction'] = 'Restriction';
$lang['web_access_control_time_rule'] = 'Time-of-Day Access Control';
$lang['web_access_control_type'] = 'Type';
$lang['web_access_control_web_access_control'] = 'Web Access Control';
$lang['web_access_control_within'] = 'Within';
$lang['web_access_control_within_range'] = 'Within time restrictions';
