<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['web_access_control_add_time'] = 'Dodaj przedział czasu';
$lang['web_access_control_app_description'] = 'Kontrola dostępu do internetu umożliwia administratorowi wymuszenie pory dnia na dostęp do internetu dla grup lub komputerów (adresów IP lub MAC) używając serwera Proxy.';
$lang['web_access_control_app_name'] = 'Kontrola dostępu do internetu';
$lang['web_access_control_apply_group'] = 'Zastosuj kontrolę dostępu dla grupy';
$lang['web_access_control_apply_ip'] = 'Zastosuj kontrolę dostępu dla adresu IP';
$lang['web_access_control_apply_mac'] = 'Zastosuj kontrolę dostępu dla adresu MAC';
$lang['web_access_control_ctrl_click'] = '(CTRL + kliknięcie dla wielokrotnego zaznaczenia)';
$lang['web_access_control_day_of_week'] = 'Dzień tygodnia';
$lang['web_access_control_end_time'] = 'Czas zakończenia';
$lang['web_access_control_id_method'] = 'Metoda identyfikacji';
$lang['web_access_control_list'] = 'Lista kontroli dostępu';
$lang['web_access_control_name'] = 'Nazwa';
$lang['web_access_control_outside'] = 'Poza';
$lang['web_access_control_outside_range'] = 'Poza ograniczeniami czasu';
$lang['web_access_control_priority'] = 'Priorytet';
$lang['web_access_control_start_time'] = 'Czas rozpoczęcia';
$lang['web_access_control_time_definitions'] = 'Definicje pory dnia';
$lang['web_access_control_time_delete_warning'] = 'Ostrzeżenie: każdy wpis kontroli dostępu korzystając z tej definicji czasu zostanie usunięty.';
$lang['web_access_control_time_of_day'] = 'Pora dnia';
$lang['web_access_control_time_restriction'] = 'Ograniczenie';
$lang['web_access_control_time_rule'] = 'Kontrola dostępu pory dnia';
$lang['web_access_control_type'] = 'Typ';
$lang['web_access_control_web_access_control'] = 'Kontrola dostępu do internetu';
$lang['web_access_control_within'] = 'W ramach';
$lang['web_access_control_within_range'] = 'W ramach ograniczeń czasowych';
